DROP DATABASE IF EXISTS app;
CREATE DATABASE app;
\connect app

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

CREATE TABLE TIPO_VIA(
	ID INTEGER NULL,
	NOMBRE TEXT NULL
);

CREATE TABLE VIA(
	ID INTEGER NULL,
	NOMBRE TEXT NULL,
	TIPO_VIA_ID INTEGER NULL
);

CREATE TABLE NODO(
	ID INTEGER NULL,
	LONGITUD FLOAT NULL,
	LATITUD FLOAT NULL,
	GEOM GEOMETRY(POINT ,4326)
);

CREATE TABLE ARISTA(
	ID INTEGER NULL,
	ID_NODO_ORIGEN INTEGER NULL,
	ID_NODO_DESTINO INTEGER NULL,
	VIA_ID INTEGER NULL,
	DISTANCIA FLOAT NULL,
	GEOM GEOMETRY(LINESTRING, 4326)
);

CREATE TABLE CONTENEDOR(
	ID INTEGER NULL,
	NOMBRE TEXT NULL,
	GEOM GEOMETRY(GEOMETRY, 4326)
);

CREATE TABLE INCIDENTE(
	ID INTEGER NULL,
	ARISTA_ID INTEGER NULL,
	FECHA_REGISTRO TIMESTAMP,
	ESTADO_INCIDENTE_ID INTEGER NULL,
	LIKES INTEGER NULL,
	GEOM GEOMETRY(GEOMETRY, 4326)
);

CREATE TABLE ESTADO_INCIDENTE(
	ID INTEGER NULL,
	DESCRIPCION TEXT NULL
);

CREATE TABLE POST(
	ID INTEGER NULL,
	FOTO TEXT NULL,
	COMENTARIO TEXT NULL,
	USUARIO_ID INTEGER
);

CREATE TABLE USUARIO(
	ID INTEGER NULL,
	NOMBRE TEXT NULL
);

CREATE TABLE LUGAR(
	ID INTEGER NULL,
	NOMBRE TEXT NULL,
	GEOM GEOMETRY(POINT, 4326)
);


COPY TIPO_VIA(ID, NOMBRE) FROM '/home/jose/Documents/HACKATON/output/o1_tipovia.csv' WITH CSV HEADER DELIMITER '|';
COPY VIA(ID, NOMBRE, TIPO_VIA_ID) FROM '/home/jose/Documents/HACKATON/output/o2_via.csv' WITH CSV HEADER DELIMITER '|';
COPY NODO(ID, LONGITUD, LATITUD, GEOM) FROM '/home/jose/Documents/HACKATON/output/o3_nodo.csv' WITH CSV HEADER DELIMITER '|';
COPY ARISTA(ID, ID_NODO_ORIGEN, ID_NODO_DESTINO, VIA_ID, DISTANCIA, GEOM) FROM '/home/jose/Documents/HACKATON/output/o4_arista.csv' WITH CSV HEADER DELIMITER '|';

