COPY TIPO_VIA(ID, NOMBRE) FROM '/home/jose/Documents/HACKATON/output/o1_tipovia.csv' WITH CSV HEADER DELIMITER '|';
COPY VIA(ID, NOMBRE, TIPO_VIA_ID) FROM '/home/jose/Documents/HACKATON/output/o2_via.csv' WITH CSV HEADER DELIMITER '|';
COPY NODO(ID, LONGITUD, LATITUD, GEOM) FROM '/home/jose/Documents/HACKATON/output/o3_nodo.csv' WITH CSV HEADER DELIMITER '|';
COPY ARISTA(ID, ID_NODO_ORIGEN, ID_NODO_DESTINO, VIA_ID, DISTANCIA, GEOM) FROM '/home/jose/Documents/HACKATON/output/o4_arista.csv' WITH CSV HEADER DELIMITER '|';

